# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_auto_20170912_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departament',
            old_name='something',
            new_name='company',
        ),
    ]
