# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_auto_20170912_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departament',
            name='boss',
        ),
    ]
